components/hostobjects/org.jaggeryjs.hostobjects.db/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.feed/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.file/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.jaggeryparser/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.log/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.oauth/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.registry/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.stream/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.uri/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.web/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xhr/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xslt/pom.xml
components/hostobjects/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt.stub/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt.ui/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.core/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.deployer/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.tools/pom.xml
components/jaggery-core/pom.xml
components/pom.xml
components/script-engine/org.jaggeryjs.scriptengine/pom.xml
components/script-engine/pom.xml
features/org.jaggeryjs.feature/pom.xml
features/org.jaggeryjs.server.feature/pom.xml
features/org.jaggeryjs.ui.feature/pom.xml
features/pom.xml
pom.xml

Revert "merging release 0.10.2"

---

components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/src/main/java/org/jaggeryjs/jaggery/app/mgt/TomcatJaggeryWebappsDeployer.java
components/jaggery-core/org.jaggeryjs.jaggery.core/src/main/java/org/jaggeryjs/jaggery/core/JaggeryCoreConstants.java

Adding Servlet Filter support with below example configuration format (please check filters and filterMappings sections of attachments)
[jaggery.conf.txt](https://github.com/wso2/jaggery/files/214408/jaggery.conf.txt)

Adding Servlet Filter support

---

components/hostobjects/org.jaggeryjs.hostobjects.xhr/src/main/java/org/jaggeryjs/hostobjects/xhr/XMLHttpRequestHostObject.java

This is the fix for host name verification skip in local environment.

Fix for Host Name Verification

---

components/jaggery-core/org.jaggeryjs.jaggery.core/src/main/resources/META-INF/scripts/http.js

Fix formatting issues mentioned in comment https://github.com/wso2/jaggery/pull/123#discussion_r70970389

Fix formatting issues in the file

---

components/hostobjects/org.jaggeryjs.hostobjects.xhr/src/main/java/org/jaggeryjs/hostobjects/xhr/XMLHttpRequestHostObject.java

Removed usage of 'org.wso2.ignoreHostnameVerification' property since this property will no longer be used

Remove 'org.wso2.ignoreHostnameVerification' property

---

components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/src/main/java/org/jaggeryjs/jaggery/app/mgt/TomcatJaggeryWebappsDeployer.java
components/jaggery-core/org.jaggeryjs.jaggery.core/src/main/java/org/jaggeryjs/jaggery/core/JaggeryCoreConstants.java

Additing servlet, listener and context param registration using jaggery.conf

 Additing servlet, listener and context param registration using jaggery.conf

---

components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/src/main/java/org/jaggeryjs/jaggery/app/mgt/TomcatJaggeryWebappsDeployer.java
components/jaggery-core/org.jaggeryjs.jaggery.core/src/main/java/org/jaggeryjs/jaggery/core/JaggeryCoreConstants.java

Reverts wso2/jaggery#177 as mistakenly committed for a released public branch

Revert " Additing servlet, listener and context param registration using jaggery.conf"

---

components/hostobjects/org.jaggeryjs.hostobjects.xhr/src/main/java/org/jaggeryjs/hostobjects/xhr/XMLHttpRequestHostObject.java
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt.ui/src/main/resources/web/jaggeryapp-mgt/uploadjaggeryapp.jsp
components/jaggery-core/org.jaggeryjs.jaggery.core/src/main/java/org/jaggeryjs/jaggery/core/listeners/WebAppSessionListener.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/RhinoTopLevel.java

Port master branch fixes to 0.12.x branch. All the fixes are done to the master branch which is not compatible with C4 based branches. So we get these fixes to 0.12.x branch to do the release for c4 based products
Port master branch fixes to 0.12.x branch. All the fixes are done to the master branch which is not compatible with C4 based branches. So we get these fixes to 0.12.x branch to do the release for c4 based products
Port master branch fixes to 0.12.x branch. All the fixes are done to the master branch which is not compatible with C4 based branches. So we get these fixes to 0.12.x branch to do the release for c4 based products
NA
NA
NA
NA
NA
NA
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs …

Port master branch fixes to 0.12.x branch

---

components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/EngineConstants.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/cache/CacheManager.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/cache/CachingContext.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/cache/ContextWrapper.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/cache/PackageWrapper.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/cache/ScriptCachingContext.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/cache/TenantWrapper.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/JaggeryContext.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/JavaScriptHostObject.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/JavaScriptMethod.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/JavaScriptModule.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/JavaScriptProperty.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/JavaScriptScript.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/RhinoClassShutter.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/RhinoContextFactory.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/RhinoEngine.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/engine/RhinoTopLevel.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/exceptions/ScriptException.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/security/RhinoSecurityController.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/security/RhinoSecurityDomain.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/security/RhinoURISecurityDomain.java
components/script-engine/org.jaggeryjs.scriptengine/src/main/java/org/jaggeryjs/scriptengine/util/HostObjectUtil.java

Add missing license files in the script-engine module
Add missing license files in the script-engine module

Add missing license files in script-engine module

---

components/jaggery-core/org.jaggeryjs.jaggery.core/src/main/java/org/jaggeryjs/jaggery/core/manager/ModuleManager.java

This PR is to close the XML stream properly so that the resource is released.

Close the stream propely

---

pom.xml

> Upgrade the following versions.
- kernel
- registry
- identity-framework
- axis2
- axiom
- rampart

Upgrade axis2,axiom versions.

---

components/hostobjects/org.jaggeryjs.hostobjects.db/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.feed/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.file/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.jaggeryparser/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.log/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.oauth/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.registry/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.registry/src/main/java/org/jaggeryjs/hostobjects/registry/internal/RegistryHostObjectServiceComponent.java
components/hostobjects/org.jaggeryjs.hostobjects.stream/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.uri/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.web/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xhr/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xslt/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/src/main/java/org/jaggeryjs/jaggery/app/mgt/internal/JaggeryappManagementServiceComponent.java
components/jaggery-core/org.jaggeryjs.jaggery.core/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.deployer/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.tools/pom.xml
components/script-engine/org.jaggeryjs.scriptengine/pom.xml
pom.xml

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Change the scr doc comment to component annotation

---

components/hostobjects/org.jaggeryjs.hostobjects.db/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.feed/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.file/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.jaggeryparser/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.log/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.oauth/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.registry/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.registry/src/main/java/org/jaggeryjs/hostobjects/registry/internal/RegistryHostObjectServiceComponent.java
components/hostobjects/org.jaggeryjs.hostobjects.stream/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.uri/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.web/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xhr/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xslt/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xslt/src/main/java/org/jaggeryjs/hostobjects/xslt/XSLTHostObject.java
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/src/main/java/org/jaggeryjs/jaggery/app/mgt/internal/JaggeryappManagementServiceComponent.java
components/jaggery-core/org.jaggeryjs.jaggery.core/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.core/src/main/java/org/jaggeryjs/jaggery/core/manager/ModuleManager.java
components/jaggery-core/org.jaggeryjs.jaggery.deployer/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.tools/pom.xml
components/script-engine/org.jaggeryjs.scriptengine/pom.xml
pom.xml

Cherry-picked commits from master

Milestone 1

---

components/hostobjects/org.jaggeryjs.hostobjects.db/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.feed/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.file/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.jaggeryparser/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.log/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.oauth/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.registry/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.stream/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.uri/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.web/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xhr/pom.xml
components/hostobjects/org.jaggeryjs.hostobjects.xslt/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt.stub/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.core/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.deployer/pom.xml
components/jaggery-core/org.jaggeryjs.jaggery.tools/pom.xml
components/script-engine/org.jaggeryjs.scriptengine/pom.xml
features/org.jaggeryjs.server.feature/pom.xml
pom.xml

Log4j update

---

components/hostobjects/org.jaggeryjs.hostobjects.log/src/main/java/org/jaggeryjs/hostobjects/log/LogHostObject.java

removing log4j in jaggery Log

---

components/hostobjects/org.jaggeryjs.hostobjects.registry/src/main/java/org/jaggeryjs/hostobjects/registry/internal/RegistryHostObjectServiceComponent.java

change component name

---

features/org.jaggeryjs.feature/pom.xml
pom.xml

add kernel.feature.version to 4.5.0

add kernel.feature.version to 4.5.0

---

features/org.jaggeryjs.server.feature/pom.xml

> Introduce new version property for the feature compatible version

Introduce new version property for the feature compatible version

---

components/jaggery-core/org.jaggeryjs.jaggery.tools/src/main/java/org/jaggeryjs/jaggery/tools/CommandLineClient.java
pom.xml

> Update kernel version and remove log4j2 removed methods

Update kernel version and remove log4j2 removed methods

---

components/jaggery-core/org.jaggeryjs.jaggery.app.mgt/src/main/java/org/jaggeryjs/jaggery/app/mgt/TomcatJaggeryWebappsDeployer.java
pom.xml

> This PR will update dependency versions and remove virtual hosts logic.

Update dependency versions and remove virtual hosts logic

---

components/hostobjects/org.jaggeryjs.hostobjects.xhr/src/main/java/org/jaggeryjs/hostobjects/xhr/XMLHttpRequestHostObject.java

This PR fixes issue wso2/product-apim#9465

Fix not honouring the non Proxy ports
